### ISSUE TITLE
Formik? Took: 5800ms?

### ISSUE THREAD

**Issue by effortlesscoding** [bluebill1049/react-hook-form-performance-compare#6]
Hey guys.

How do I read the Formik's screenshot?

It looks like main.js script stopped at 5000ms. The purple bar stopped at around 5800ms, but the green bar (I think it is PAINTing phase, right?) stopped at around 6250ms.

Although it looks like react-hook-form IS faster, I cannot find out how the conclusion of 5800ms was made.

**Comment by bluebill1049** [comment]
Take a look at the screenshot that I got (3 of them you can zoom in for detail), I guess the idea to showcase that for React Hook Form you don't need wrapper component which means less components to render and less time to mount all those inputs.
